Repository rropen/team-app, pull requests merged in 2025-06, with the labels that each got.

#35 Add missing migration from previous PR
  teams_source/teams_app/migrations/0011_alter_relationship_role.py
Labels: backend, debt

#37 TA - Add cache table to setup script
  setup_venv.bat
  setup_venv.sh
Labels: backend, debt

#39 Add User API view
  teams_source/teams_app/teams_api/api_serializer.py
  teams_source/teams_app/teams_api/api_urls.py
  teams_source/teams_app/teams_api/api_views.py
Labels: backend, feature

#41 TA (PR): Readded "email" into both fields
  teams_source/teams_app/teams_api/api_serializer.py
  teams_source/teams_app/teams_api/serializers/teams_list.py
Labels: backend, defect

#44 TA: Fix syntax error that causes setup script to crash
  setup_venv.sh
Labels: debt, defect

#45 TA: Standardise setup script name
  setup.bat
  setup.sh
Labels: debt

#46 TA: Port codebase to UV + add and complement relevant documentation
  .python-version
  CONTRIBUTING.md
  DEVELOPER.md
  README.md
  SBASEGUIDE.md
  SECURITY.md
  pyproject.toml
  requirements.txt
  setup.bat
  setup.sh
Labels: debt

#50 TA: Update docs
  .pre-commit-config.yaml
  DEVELOPER.md
  README.md
  teams_source/teams_app/apps.py
  teams_source/teams_app/signals.py
Labels: backend, defect, documentation
